"use client"

import { useRef, useEffect } from 'react'
import { supabase } from '@/lib/supabase/client'
import { useToast } from '@/components/ui/use-toast'
import { useAuth } from '@/contexts/AuthContext'

const VisitorNotification = () => {
    // const supabase = createClientComponentClient() // Removed
    const { toast } = useToast()
    const { profile } = useAuth()
    const audioRef = useRef<HTMLAudioElement | null>(null)

    useEffect(() => {
        // Simple notification sound (beep)
        // using a base64 data URI for a simple "ding"
        audioRef.current = new Audio("data:audio/wav;base64,UklGRl9vT19XQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YU")
        // Note: The above is a placeholder empty/invalid base64 for brevity. 
        // I will use a real short beep base64 in the actual component below.

        // Better: Use a public URL or a reliable beep. 
        // Let's use a simple sine wave generated by Web Audio API or a reliable data URI.
        // For simplicity in this file, I'll use a functional beep function using AudioContext 
        // OR a valid data URI.
    }, [])

    const playNotificationSound = () => {
        try {
            const ctx = new (window.AudioContext || (window as any).webkitAudioContext)()
            const osc = ctx.createOscillator()
            const gain = ctx.createGain()

            osc.connect(gain)
            gain.connect(ctx.destination)

            osc.type = 'sine'
            osc.frequency.setValueAtTime(500, ctx.currentTime)
            osc.frequency.exponentialRampToValueAtTime(1000, ctx.currentTime + 0.1)

            gain.gain.setValueAtTime(0.5, ctx.currentTime)
            gain.gain.exponentialRampToValueAtTime(0.01, ctx.currentTime + 0.5)

            osc.start()
            osc.stop(ctx.currentTime + 0.5)
        } catch (e) {
            console.error("Audio playback failed", e)
        }
    }

    useEffect(() => {
        if (!process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL.includes('placeholder')) return

        const channel = supabase
            .channel('visitor_updates')
            .on(
                'postgres_changes',
                {
                    event: 'INSERT',
                    schema: 'public',
                    table: 'visitors',
                },
                (payload) => {
                    const newVisitor = payload.new as any

                    // Check if this visitor is for the current user's unit
                    // User needs to have units fetched. 
                    // To avoid complex fetching here, we can rely on `profile.unit_id` if available 
                    // or just notify if we can verify the unit.

                    // Ideally, profile should have unit_id.
                    if (profile?.unit_id && newVisitor.visiting_unit_id === profile.unit_id) {
                        // Play Sound
                        playNotificationSound()

                        // Show Toast
                        toast({
                            title: "New Visitor Request",
                            description: `${newVisitor.visitor_name} is requesting entry.`,
                            variant: "default",
                        })
                    }
                }
            )
            .subscribe()

        return () => {
            supabase.removeChannel(channel)
        }
    }, [supabase, profile, toast])

    return null // Invisible component
}

export default VisitorNotification
